version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    networks:
      - wordpress_net
    depends_on:
      - db
    volumes:
      - ./wp/wp-content/themes:/var/www/html/wp-content/themes
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    # volumes:
    #   - ./wait-for-db.sh:/wait-for-db.sh
    # command: ["/bin/sh", "/wait-for-db.sh"]

  db:
    image: mariadb:10.6
    platform: linux/amd64
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
    driver: bridge
